Fix problem when using binary packages.
Add BUILDLINK_API_DEPENDS.libotr due to:
configure: error: libotr 3.2.0 or newer is required.

The real problem was undefined reference to gcry_cipher_setkey
and gcry_cipher_setctr. Looked at various versions on different
architectures and it appears even though the headers were there,
they weren't defined in the library until libgcrypt-1.4.3 --
so define BUILDLINK_ABI_DEPENDS.libgcrypt.

Bump PKGREVISION.