Update to version 1.3.1_13. Addresses security issue   http://sunsolve.sun.com/search/document.do?assetkey=1-26-57591-1
Changes since _12 according to
  http://java.sun.com/j2se/1.3/ReleaseNotes.html

Can't display localized exception messages of the native method correctly
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0